### ISSUE TITLE
How to use OAuth2 with new version 3.0.2?

### ISSUE THREAD

**Issue by jagdish-176** [oas-tools/oas-tools.github.io#12]
### Discussed in https://github.com/orgs/oas-tools/discussions/11

I have migrated from swagger-tools to oas-tools@2.x.x and now trying to migrate from 2.x to 3.x 

Previously with 2.x I have security handler as below where I could get token for verification
OAuth2 = async (req, def, scopes, next) =>{ /*validate token from req.Authorization */}

Now with 3.x, I'm unable to get token. I would appreciate quick help on this 
OAuth2: (secDef, secScope) => { /* OAuth authentication */ } // How do we get token here?

**Comment by alesancor1** [comment]
Closed as discussed in GH Discussions. It will be reopened if changes in the coded are required.
